volumes:
  db-data:

services:
  db:
    image: postgres:14
    container_name: memoapp-prisma-db
    volumes:
      - db-data:/var/lib/postgresql/prisma-db/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
